### PR TITLE
Create 2022-06-14.md

### PR DESCRIPTION
**Pull request by orchid00**
Started the draft for Kelly's talk

### CODE REVIEW

**Comment by jcohen02** [comment]
Thanks for setting this up @orchid00.

**Comment by orchid00** [comment]
Hi @jcohen02 , 

I think I've updated all the pages that are needed.

**Comment by orchid00** [comment]
Now added the right image. :)

**Comment by jcohen02** [comment]
Many thanks for creating the new event page @orchid00.

**Pull request merged**
